---
- hosts: all
  become: yes
  tasks:
  - name: I want to install apache werbserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: I want to start webserver
    service: 
      name: apache2
      state: started