---
- hosts: 172.31.20.36
  become: yes
  tasks:

  - name: install apache2
    apt:
     name: apache2
     state: present
  
  - name: copy dynamic file into node side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html